#!/usr/bin/ruby -w

require 'csv'

data       = CSV.open(ARGV.shift).to_a
velocities = Hash.new do |h, k|
  h[k] = Hash.new do |ih, ik|
    ih[ik] = []
  end
end



data.each do |speeds|
  num   = speeds[0]
  speed = speeds[1]
  speeds[2..-1].each_with_index do |type, index|
    velocities[num][speed][index] = type
  end
end


velocities.each_pair do |train, speeds|
  puts "    // Velocity mapping for #{train}"

  speeds.each_pair do |speed, types|
    types.each_with_index do |type, index|
      puts "        ctxt->velocity[#{speed}][#{index}] = #{type};"
    end
  end
end
